# Permalinks
permalink:        pretty

# Setup
url: /

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl: http://xiaowoniu22.github.io
title:  Tracy Guo'blog
email: guoxiaoting949@163.com

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  A pretentious two-column [Jekyll](http://jekyllrb.com/) theme, stolen by [`@qwtel`](https://twitter.com/qwtel)
  from [Hyde](http://hyde.getpoole.com).
  You could say it was.. [hydejacked](http://media3.giphy.com/media/makedRIckZBW8/giphy.gif).

# The tags listed as entries in the sidebar
sidebar_tags:     [jekyll, hyde]

# Fallback image and color if not overwritten for tag or post
image:            /public/img/nap.jpg
color:            '#A85641'

author:
  name:           'Tracy Guo'

  # Setting social media usernames will add icons at the bottom of the sidebar
  github:         xiaowoniu22

  # Setting a disqus username will enable the comment section
  disqus:

  # This photo will be used in the about section
  photo:          http://tva2.sinaimg.cn/crop.0.0.750.750.180/006dXbLqjw8f3ychzjqepj30ku0kvdhb.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
   Hello! I'm Tracy Guo.

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
